# This is a basic workflow to help you get started with Actions

name: Refresh_DB

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: P@ssw0rd
          MYSQL_DATABASE: mlb_db
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - run: 
          sudo service mysql start;
          mysql -u root -p P@ssw0rd
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # this Action should follow steps to set up Python build environment
      
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
      

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python .github/workflows/Automated_Data_Collection.py
